version: '3'
services:
  db:
    image: postgres
    environment:
        POSTGRES_PASSWORD: SECCURE12345
    ports:
      - "8001:5432"
  web:
    build: .
    volumes:
      - ./:/sampleService
    ports:
      - "9000:9000"
    depends_on:
      - db
    command: sbt run
